### ISSUE TITLE
FreeBSD 13-1 not availble for CSP

### ISSUE THREAD

**Issue by Mark-gx** [dmauser/opnazure#45]
Hey all,

Unfortunately FreeBSD 13-1 is not yet approved for CSP subscriptions in the azure marketplace. If there would be any way to still offer a choice for older opnsense build running under freebsd 13-0 it would be much appreciated.

**Comment by Welasco** [comment]
Hi @Mark-gx , sorry for the delay here.
I believe the problem you are having is related to accept license from FreeBSD images. Looks like they are requiring it to accepted now prior to the first utilization of this new image.

Can you please try the following command and try deploy it again?
az vm image terms accept --urn thefreebsdfoundation:freebsd-13_1:13_1-release:13.1.0 -o none

**Comment by Mark-gx** [comment]
Hi @Welasco  no worries, thanks for your hard work!

I ran the command and waited a bit including a relog, no change sadly.

<img width="876" alt="CSPSubscription" src="https://user-images.githubusercontent.com/113065358/222524273-84667d2b-2508-4962-9176-7601a402f110.png">

**Comment by cehser** [comment]
I ran into the same issue today. Is there anything anybody apart from the FreeBSD Foundation can do about this?

**Comment by Welasco** [comment]
@cehser , really sorry to hear that.
Unfortunately we don't have much option here.
Microsoft has an official image for FreeBSD 12. We were using this image before but unfortunately we received an official message from the team who handle images in Azure and their answer was to use the image from FreeBSD Foundation.

I can work on it and allow the change of the FreeBSD image so you could try to go back to the Microsoft Image, but that would be a blocker for future because the OPNSense bootstrat script requires FreeBSD 13.1 now.

We are in a chicken and egg situation.

**Comment by christopherusky** [comment]
I am in a situation whereby I was told that under the CSP the FreeBSD foundation images were not availble from the Azure store. Having made a nuisance of myself, there is now an exception being carved out to permit the required images to be availblem but ONLY if I move to FreeBSD 13.2 since 13.1 is now out of support. 

So solution is to persist with the ask at your CSP.

Question is will the bootstrap script work with 13.2?
